### DISCUSSION TITLE
How can we give Master URL while submitting the app?

### DISCUSSION THREAD

**Discussion by Premkumar7402** [hussein-awala/spark-on-k8s#116] [Q&A] [answered]
Hi, 

i'm trying to submitting the spark app by using below from one server to another server where spark k8 cluster present. 

```python
client_obj.submit_app(
                image=config.get("spark.kubernetes.container.image","spark-image"),
                app_path=config.get("spark.kubernetes.app_path","/opt/spark/examples/jars/spark-examples_2.12-3.4.3.jar"),
                app_name=config.get("spark.kubernetes.app_name","test-pi"),
                namespace=config.get("spark.kubernetes.namespace","spark"),
                spark_conf=config.get("spark.properties",{})
                #ui_reverse_proxy=True,
            ) 
```

I see the driver pod gets created in K8S setup. my question is where we can give --master url and --deploy-mode args while submitting the app? 

like below: 

```bash
./bin/spark-submit \
    --master k8s://https://<k8s-apiserver-host>:<k8s-apiserver-port> \
    --deploy-mode cluster \
    --name spark-pi \
    --class org.apache.spark.examples.SparkPi \
```

**Comment by hussein-awala** [comment, marked as answer]
Hi @Premkumar7402,

For deploy mode, the package is designed to create a new pod for the driver, similar to what Spark CLI does in cluster mode, so we can say that only the cluster mode is supported in the package.

For master URL, the package uses the official [Python Kubernetes client](https://github.com/kubernetes-client/python) to create and manage the Spark application resources, if you have any advanced configuration to pass, you can use the client's argument `k8s_client_manager` with an instance of `KubernetesClientManager` or an instance of your own client manager (subclass of `KubernetesClientManager`), and/or update the kubernetes config file, for ex:
kubeconfig.yml:
```yml
apiVersion: v1
clusters:
- cluster:
    server: https://new-cluster-url:6443
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-user
  name: my-context
- context:
    ...
  name: another-context
current-context: another-context
kind: Config
preferences: {}
users:
- name: my-user
  user:
    token: my-access-token
```
python code:
```python
client_obj = SparkOnK8S(
    k8s_client_manager=KubernetesClientManager(context="my-context"),
)
client_obj.submit_app(
  image=config.get("spark.kubernetes.container.image","spark-image"),
  app_path=config.get("spark.kubernetes.app_path","/opt/spark/examples/jars/spark-examples_2.12-3.4.3.jar"),
  app_name=config.get("spark.kubernetes.app_name","test-pi"),
  namespace=config.get("spark.kubernetes.namespace","spark"),
  spark_conf=config.get("spark.properties",{})
  #ui_reverse_proxy=True,
)
```
