### ISSUE TITLE
Spark UI in Azure Kubernetes Service

### ISSUE THREAD

**Issue by quinnsp06** [hussein-awala/spark-on-k8s#22]
Hi Hussein,

When executing the steps on an AKS cluster I receive the following errors:

I run the start API I get the error below and in the Browser it gives Internet Server Error. Remembering that to access the AKS UI POD on port 4040 I have to port-forward to localhost on port 8080:

  File "/home/elcio/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -2] Name or service not known

kubectl port-forward pod/testapp-20240308105234-driver 8080:4040
Forwarding from [::1]:8080 -> 4040
Handling connection for 8080
Handling connection for 8080
E0308 10:56:16.457516    5406 portforward.go:409] an error occurred forwarding 8080 -> 4040: error forwarding port 4040 to pod dadf61ac7c8d997b5c4148145abc477a6b76c26831c58a0469a7db34dd60540a, uid : failed to execute portforward in network namespace "/var/run/netns/cni-7df48b40-aa72-787f-fe1a-41f2b6711cdf": failed to connect to localhost:4040 inside namespace "dadf61ac7c8d997b5c4148145abc477a6b76c26831c58a0469a7db34dd60540a", IPv4: dial tcp4 127.0.0.1:4040: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found
E0308 10:56:16.468872    5406 portforward.go:394] error copying from local connection to remote stream: EOF
error: lost connection to pod

<img width="908" alt="image" src="https://github.com/hussein-awala/spark-on-k8s/assets/99848442/863bfd8e-00fd-4996-a8a6-33837471e129">

**Comment by hussein-awala** [comment]
Do you have a default `deny all` network policy in your cluster? something like:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```

If so, could you try to add a new network policy in the webserver namespace to permit the webserver pod to route the traffic to the driver pods? something like:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-redirect-traffic
spec:
  podSelector:
    matchLabels:
      app: spark-webserver
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: <your namespace>
    ports:
    - protocol: TCP
      port: 8000
  egress:
  - to:
    - podSelector:
        matchLabels:
          spark-role: driver
    ports:
    - protocol: TCP
      port: 4040
```
